const db = require('../config/db');
const { fetchLiveWeather } = require('./weatherService');
const { HydrologicalAgent, InundationAgent, RoutingAgent, MultilingualAlertAgent } = require('./agents');

const runAIFloodPrediction = async (lat = 13.0827, lon = 80.2707) => {
  try {
    // 1. Get Live Weather & Forecast
    const weatherResult = await fetchLiveWeather(lat, lon);
    const currentWeather = weatherResult.current;
    const forecast = weatherResult.forecast;

    // 2. Fetch Latest Sensor Water Levels
    const sensorResult = await db.query(
      'SELECT sensor_id, water_level, latitude, longitude, status FROM sensor_data'
    );
    const sensors = sensorResult.rows;

    // 3. Fetch Historical Averages
    const historyResult = await db.query(
      'SELECT AVG(rainfall) as avg_rain, AVG(temperature) as avg_temp FROM historical_weather'
    );
    const avgHistoricalRain = historyResult.rows[0].avg_rain 
      ? parseFloat(historyResult.rows[0].avg_rain) 
      : 20.0;

    // Agentic Pipeline
    
    // Agent 1: Hydrological Analysis
    const hydroResult = await HydrologicalAgent.analyze(sensors, currentWeather, forecast, avgHistoricalRain);
    
    // Agent 2: Inundation Mapping
    const inundationResult = await InundationAgent.simulatePropagation(hydroResult.riskLevel, hydroResult.probability, sensors);
    
    // Agent 3: Evacuation Routing
    const routes = await RoutingAgent.generateRoutes(inundationResult.floodedAreas);
    
    // Agent 4: Multilingual Alerts Generation (HITL pending_approval state)
    const alertData = await MultilingualAlertAgent.synthesizeAlert(hydroResult.riskLevel, hydroResult.probability, inundationResult.floodedAreas);

    // Save Prediction
    const locationString = `${lat.toFixed(4)}, ${lon.toFixed(4)}`;
    const reasonString = `AI Analysis: Hydrological risk ${hydroResult.riskLevel}. Max water level: ${hydroResult.maxWaterLevel.toFixed(2)}m. Expected rain: ${hydroResult.forecastRainSum.toFixed(1)}mm.`;
    
    await db.query(
      `INSERT INTO flood_predictions (risk_level, probability, location, reason)
       VALUES ($1, $2, $3, $4)`,
      [hydroResult.riskLevel, hydroResult.probability, locationString, reasonString]
    );

    // If an alert was generated by the Multilingual Agent, save it as pending_approval
    if (alertData) {
      await db.query(
        `INSERT INTO alerts (title, message, severity, location, status, target_population_reach)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [alertData.title, alertData.message, alertData.severity, alertData.location, alertData.status, alertData.targetPopulation]
      );
    }

    return {
      riskLevel: hydroResult.riskLevel,
      probability: hydroResult.probability,
      reasons: [reasonString],
      affectedAreas: inundationResult.floodedAreas.map(a => a.id),
      routesGenerated: routes.length,
      alertGenerated: !!alertData,
      timestamp: new Date()
    };

  } catch (error) {
    console.error('AI Flood Prediction engine error:', error.message);
    throw error;
  }
};

module.exports = { runAIFloodPrediction };
